# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sizeguide"
client_id = "bff71b06d606cba86cb876f7302d3da2"
application_url = "https://sizeguide-cyan.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
  "https://sizeguide-cyan.vercel.app/api/auth",
  "https://sizeguide-cyan.vercel.app/auth/callback",
  "https://sizeguide-cyan.vercel.app/auth/shopify/callback"
]

[webhooks]
api_version = "2026-10"

[webhooks.privacy_compliance]
customer_deletion_url = "https://sizeguide-cyan.vercel.app/webhooks/customers/redact"
customer_data_request_url = "https://sizeguide-cyan.vercel.app/webhooks/customers/data_request"
shop_deletion_url = "https://sizeguide-cyan.vercel.app/webhooks/shop/redact"

[extensions.theme]
handle = "sizeguide-extension"

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://sizeguide-cyan.vercel.app/api"
subpath = "sizeguide"
prefix = "apps"
